### ISSUE TITLE
support for non-TTY terminals

### ISSUE THREAD

**Issue by anmonteiro** [Centiq/historic-readline#1]
Hi,

I'm considering using your library instead of [readline-history](https://www.npmjs.com/package/readline-history), which seems unmaintained.

However, it seems that both suffer from a problem: as stated in [Node's docs for readline](https://nodejs.org/api/readline.html#readline_readline_createinterface_options), the history caching mechanism is only initialized when `terminal` is true in the configuration map passed to `createInterface`.

I'm developing an app that I want to be configurable with respect to having TTY streams or not. Currently it'll throw an error in non-TTY mode because `historic-readline` will try to [push to an inexistent property](https://github.com/Centiq/historic-readline/blob/master/rl.js#L42).

Thanks!

**Comment by woverton** [comment]
Thanks for flagging it up, I'll look into it :)

**Comment by woverton** [comment]
Can you try this fix before I merge it? 
https://github.com/Centiq/historic-readline/tree/bugfix-nontty

Thanks!

**Comment by anmonteiro** [comment]
working great, thanks!

**Comment by woverton** [comment]
Sorted :)
